---
engine:
  name: docker

provisioner:
  name: ansible
  extra_args:
    - --diff
  env:
    ANSIBLE_NOCOLOR: False

verifier:
  name: goss
  extra_args:
    - --format
    - tap

instances:
  - name: rockylinux-9.1
    image: rockylinux-systemd:9.1
